
###
//CADASTRAR
POST https://localhost:5001/odonto/consulta/create
Content-Type: application/json

{
    "Nome_consulta" : "Consunta paciente 2",
    "Descricao_Consulta" : "PAciente tem coÇeira anal"
}

###
//LISTAR
GET  https://localhost:5001/odonto/consulta/list
Content-Type: application/json

###
//Busca por Id
GET https://localhost:5001/odonto/consulta/getbyid/1

###
//ALTERAR
PUT  https://localhost:5001/odonto/consulta/update
Content-Type: application/json

{
    "Id" : 1,
    "Nome" : "Caio"
}

###
//EXCLUIR POR ID
POST https://localhost:5001/odonto/consulta/deletebyid
Content-Type: application/json

{
    "Id" : 1
}

###
//EXCLUIR POR NOME
DELETE https://localhost:5001/odonto/consulta/delete/Consunta paciente 2
