
###
//CADASTRAR
POST https://localhost:5001/odonto/consulta/create
Content-Type: application/json

{
    "Nome_consulta" : "Consunta paciente x",
    "Descricao_Consulta" : "PAciente tem coÇeira anal"
}

###
//LISTAR
GET  https://localhost:5001/odonto/consulta/list
Content-Type: application/json

###
//EXCLUIR
POST https://localhost:5001/odonto/consulta/delete 
Content-Type: application/json

{
    "Id" : 1
}

###
//ALTERAR
POST https://localhost:5001/odonto/consulta/update
Content-Type: application/json

{
    "Id" : 1,
    "Nome" : "Caio"
}