###
//CADASTRAR
POST https://localhost:5001/odonto/paciente/create
Content-Type: application/json

{
    "Nome" : "Caio Roque",
    "Cpf" : "2656464",
    "Telefone" : "3655-3255",
    "Descricao" : "O paciente tem sindrome do impostor",
    "Idade" : 23
}

###
//LISTAR
GET  https://localhost:5001/odonto/paciente/list
Content-Type: application/json

###
//Busca por Id
GET https://localhost:5001/odonto/paciente/getbyid/1

###
//EXCLUIR
POST https://localhost:5001/odonto/paciente/deletebyid
Content-Type: application/json

{
   "Id" : 1
}

###
//EXCLUIR POR NOME
DELETE https://localhost:5001/odonto/paciente/delete/Caio Roque


###
//ALTERAR
PUT https://localhost:5001/odonto/paciente/update
Content-Type: application/json

{
    "Id" : 2,
    "Nome" : "Caio",
    "Descricao" : "Have fun, Dont die"
}